version: "3.8"

services:
  go-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: go-api:1.0.0
    ports:
      - "8080:8080"
    env_file:
      - .env.local
    restart: unless-stopped
