name: go-api prod

on:
  push:
    branches: [master]
  workflow_dispatch:

env:
  APP_NAME: go-api
  VERSION: 1.0.0

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24 # Set your Go version

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build
        run: make build

      - name: Test
        run: make test

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t $APP_NAME:$VERSION .
          docker tag $APP_NAME:$VERSION ${{ secrets.DOCKER_USERNAME }}/$APP_NAME:$VERSION

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/$APP_NAME:$VERSION
